### ISSUE TITLE
Editor initialization throws Exception on start

### ISSUE THREAD

**Issue by Centaur** [Centaur/scalaconsole#2]
```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not a function
    at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
    at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
    at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
    at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
    at org.scalaconsole.fxui.main.MainController$class.changed$body$3(MainController.scala:209)
    at org.scalaconsole.fxui.main.MainController$$anonfun$12.changed(MainController.scala:203)
    at org.scalaconsole.fxui.main.MainController$$anonfun$12.changed(MainController.scala:203)
```

This happend only to assembly big jar.  Works fine if start scalaconsole from sbt. Look like caused by upgrade jdk to 8u60

**Comment by Centaur** [comment]
http://stackoverflow.com/questions/32429069/loading-local-javascript-file-in-webview-in-java-8u60

**Comment by Centaur** [comment]
Problem does not get fixed in 8u66.

**Comment by Centaur** [comment]
Rejoice! This secret jdk bug has been fixed (sneakingly) in 8u72.
