### ISSUE TITLE
编译以后运行console,无法输入代码

### ISSUE THREAD

**Issue by yosaku01** [Centaur/scalaconsole#6]
是不是输入法的问题？
我的jdk是1.8.65
scala是2.11.8

启动后的异常信息是
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not a function
        at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
        at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
        at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
        at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
        at org.scalaconsole.fxui.main.MainController$$anonfun$initWebView$3.apply(MainController.scala:193)
        at org.scalaconsole.fxui.main.MainController$$anonfun$initWebView$3.apply(MainController.scala:187)
        at org.scalaconsole.fxui.FxUtil$FunctionAsChangeListener.changed(FxUtil.scala:52)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
        at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
        at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
        at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
        at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
        at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$96(URLLoader.java:829)
        at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Centaur** [comment]
这是 jdk 8u60 引入 的bug，在 8u72 才解决。详见 #2

**Comment by yosaku01** [comment]
好的，我升级一下我的jdk环境

**Comment by gogo649** [comment]
我也遇到了同样的问题，我的环境是
jdk:jdk1.8.0_131
Scala: 2.12.2 

错误日志：

`/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=50301:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/yuanjianhua/Library/Application Support/IntelliJIdea2017.1/Scala/launcher/sbt-launch.jar" xsbt.boot.Boot run
objc[1192]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x10db384c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10fbbc4e0). One of the two will be used. Which one is undefined.
[info] Loading project definition from /Users/yuanjianhua/git_ws/scalaconsole/project
[info] Set current project to ScalaConsole (in build file:/Users/yuanjianhua/git_ws/scalaconsole/)
[info] Running org.scalaconsole.fxui.ScalaConsole 
[error] Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not a function
[error] 	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:146)
[error] 	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
[error] 	at com.sun.webkit.WebPage.executeScript(WebPage.java:1509)
[error] 	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:1005)
[error] 	at org.scalaconsole.fxui.main.MainController.$anonfun$initWebView$3(MainController.scala:200)
[error] 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
[error] 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
[error] 	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
[error] 	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
[error] 	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
[error] 	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
[error] 	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1287)
[error] 	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1398)
[error] 	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1280)
[error] 	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1267)
[error] 	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2499)
[error] 	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2343)
[error] 	at com.sun.webkit.network.URLLoader.twkDidFail(Native Method)
[error] 	at com.sun.webkit.network.URLLoader.notifyDidFail(URLLoader.java:883)
[error] 	at com.sun.webkit.network.URLLoader.lambda$didFail$104(URLLoader.java:866)
[error] 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
[error] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)`
